# Generated by Django 5.0.8 on 2024-08-13 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_corrida_categoria_alter_corrida_circuito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais'),
        ),
    ]
