# Generated by Django 5.0.8 on 2024-08-13 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_equipe_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corrida',
            name='data',
        ),
    ]
