# Generated by Django 5.0.8 on 2024-08-14 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_corrida_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaautomobilismo',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='categoriaautomobilismo',
            name='fundacao',
        ),
    ]
