# Generated by Django 5.0.8 on 2024-08-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_categoriaautomobilismo_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrida',
            name='vencedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
