# Generated by Django 5.0.8 on 2024-08-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_corrida_vencedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='circuito',
        ),
    ]
