# Generated by Django 5.0.8 on 2024-08-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_calendario_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais'),
        ),
    ]
