# Generated by Django 5.0.8 on 2024-08-21 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_piloto_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipe'),
        ),
    ]
