# Generated by Django 5.0.8 on 2024-08-26 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_piloto_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='categoria_automobilismo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.categoriaautomobilismo'),
        ),
    ]
