# Generated by Django 5.0.8 on 2024-08-26 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_equipe_montadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='montadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.montadora'),
        ),
    ]
