# Generated by Django 5.0.8 on 2024-08-27 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_equipe_montadora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontuacao',
            name='corrida',
        ),
        migrations.RemoveField(
            model_name='pontuacao',
            name='piloto',
        ),
        migrations.DeleteModel(
            name='Carro',
        ),
        migrations.DeleteModel(
            name='Pontuacao',
        ),
    ]
